# Generated by Django 5.0.2 on 2024-03-27 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0003_book'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='bookModel',
        ),
    ]
