# Generated by Django 5.0.2 on 2024-04-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0005_music'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='popular',
            field=models.IntegerField(default=0),
        ),
    ]
