# Generated by Django 5.0.2 on 2024-04-24 14:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0007_rename_publish_date_book_published_date_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='publish_date',
        ),
        migrations.AlterModelTable(
            name='book',
            table='bookModel',
        ),
    ]
