# Generated by Django 5.0.2 on 2024-04-24 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0008_rename_published_date_book_publish_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
